### ISSUE TITLE
Relicense Repository - EPL+Apache

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-cli-sample-scripts#19]
As this repository contains sample source code intended to be downloaded and expanded upon, it would be better suited with an EPL+Apache 2.0 dual license.

The OMP Governing Board has approved EPL-2.0 license waivers for sample repositories in Zowe, replaced by the dual license.

To re-license this repository, all contributors should consent by responding to this issue in the affirmative.

**Comment by MarkAckert** [comment]
+1 to relicense

**Comment by dan-jast** [comment]
+1

**Comment by MikeBauerCA** [comment]
@MarkAckert @zFernand0 it appears this issue got lost. Do you have the new Apache-2.0 license text and license header that should be added to each file?

**Comment by zFernand0** [comment]
Here is a PR we can use as an example:
- https://github.com/zowe/zowe-cli-sample-plugin/pull/61
